'use client'

import { useEffect, useState } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import Link from 'next/link'
import { Bell, CheckCircle2, Clock, FileText, FolderKanban, FolderOpen, LayoutDashboard, LogOut, Menu, MessageSquare, Search, Settings, Users, X } from 'lucide-react'
import { logout } from '@/services/api'
import { Avatar, Button, Input, ThemeToggle } from './ui'

const groups = [{ label: 'Workspace', links: [['Overview', '/dashboard', LayoutDashboard], ['Projects', '/dashboard/projects', FolderKanban], ['Clients', '/dashboard/clients', Users], ['Files', '/dashboard/files', FolderOpen], ['Messages', '/dashboard/messages', MessageSquare, 3]] }, { label: 'Billing', links: [['Approvals', '/dashboard/approvals', CheckCircle2, 4], ['Invoices', '/dashboard/invoices', FileText], ['Activity', '/dashboard/activity', Clock]] }]
const titles = { '/dashboard': 'Overview', '/dashboard/projects': 'Projects', '/dashboard/clients': 'Clients', '/dashboard/files': 'Files', '/dashboard/messages': 'Messages', '/dashboard/approvals': 'Approvals', '/dashboard/invoices': 'Invoices', '/dashboard/activity': 'Activity', '/dashboard/settings': 'Settings' }
function Logo() { return <Link href="/" className="flex items-center gap-2 text-lg font-semibold text-slate-900 dark:text-slate-100"><span className="flex size-8 items-center justify-center rounded-[10px] bg-indigo-600"><span className="size-3 rounded-[4px] bg-white" /></span>Atrium</Link> }
function Nav({ onNavigate }) { const path = usePathname(); return <nav className="flex flex-1 flex-col gap-6 p-4">{groups.map((group) => <div key={group.label}><p className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-400 dark:text-slate-500">{group.label}</p><div className="flex flex-col gap-1">{group.links.map(([label, href, Icon, count]) => { const active = path === href; return <Link key={href} href={href} onClick={onNavigate} className={`flex h-9 items-center gap-3 rounded-lg px-3 text-sm transition ${active ? 'bg-indigo-50 font-medium text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300' : 'text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-white/[0.05]'}`}><Icon className="size-4" />{label}{count && <span className="ml-auto flex h-[18px] min-w-[18px] items-center justify-center rounded-full bg-indigo-600 text-[10px] text-white">{count}</span>}</Link>})}</div></div>)}</nav> }
function UserArea() { const router = useRouter(); return <div className="border-t border-slate-200 p-4 dark:border-white/[0.08]"><div className="mb-4 rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-white/[0.08] dark:bg-white/[0.03]"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium">Studio plan</span><span className="text-xs text-indigo-600 dark:text-indigo-400">Upgrade</span></div><p className="mb-2 text-xs text-slate-500 dark:text-slate-400">3 of 5 team members used</p><div className="h-1.5 rounded-full bg-slate-200 dark:bg-white/10"><div className="h-full w-3/5 rounded-full bg-indigo-500" /></div></div><div className="flex items-center gap-3 border-t border-slate-200 pt-3 dark:border-white/[0.08]"><Avatar name="Jamie Taylor" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">Jamie Taylor</p><p className="text-xs text-slate-500 dark:text-slate-400">Owner</p></div><button aria-label="Log out" onClick={() => { logout(); router.push('/login') }} className="text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-100"><LogOut className="size-4" /></button></div></div> }
export default function DashboardShell({ children }) { const [open, setOpen] = useState(false); const [notice, setNotice] = useState(false); const path = usePathname(); const router = useRouter(); useEffect(() => { if (!localStorage.getItem('atrium_user')) router.replace('/login') }, [router]); return <div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-[#0A0A0B] dark:text-slate-100"><aside className={`fixed inset-y-0 left-0 z-40 flex w-60 flex-col border-r border-slate-200 bg-white transition-transform dark:border-white/[0.08] dark:bg-[#0D0D0F] ${open ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}`}><div className="flex h-14 items-center justify-between border-b border-slate-200 px-5 dark:border-white/[0.08]"><Logo /><button aria-label="Close menu" className="lg:hidden" onClick={() => setOpen(false)}><X className="size-4" /></button></div><Nav onNavigate={() => setOpen(false)} /><UserArea /></aside>{open && <button aria-label="Close menu" onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-black/30 lg:hidden" />}<div className="lg:pl-60"><header className="sticky top-0 z-20 flex h-14 items-center gap-4 border-b border-slate-200 bg-white/80 px-4 backdrop-blur dark:border-white/[0.08] dark:bg-[#0A0A0B]/80 sm:px-6"><button aria-label="Open menu" className="lg:hidden" onClick={() => setOpen(true)}><Menu className="size-5" /></button><h1 className="hidden text-sm font-semibold sm:block">{titles[path] || 'Overview'}</h1><div className="relative ml-auto hidden max-w-md flex-1 md:block"><Search className="absolute left-3 top-2.5 size-4 text-slate-400 dark:text-slate-500" /><Input className="w-full pl-9 pr-14" placeholder="Search projects, clients, files…" /><kbd className="absolute right-2 top-1.5 rounded border border-slate-200 px-1.5 py-1 text-[10px] text-slate-400 dark:border-white/[0.08] dark:text-slate-500">⌘K</kbd></div><ThemeToggle /><Button icon aria-label="Notifications" onClick={() => setNotice(!notice)} className="relative text-slate-500 dark:text-slate-400"><Bell /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-indigo-500" /></Button><Avatar name="Jamie Taylor" size={28} />{notice && <div className="absolute right-6 top-12 w-72 rounded-xl border border-slate-200 bg-white p-4 shadow-lg dark:border-white/[0.08] dark:bg-[#111113]"><p className="text-sm font-semibold">Notifications</p><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Maya approved Homepage v3.</p></div>}</header><main className="mx-auto max-w-6xl px-6 pb-10 pt-6">{children}</main></div></div> }
